Resources:
  TeamplateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: templates
      AttributeDefinitions:
        - AttributeName: unique_id
          AttributeType: S
      KeySchema:
        - AttributeName: unique_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
